version: "3"

services:
  
  api:
    image: node:8
    user: node
    depends_on:
      - mongo
    deploy:
      replicas: 1
    working_dir: /home/api
    environment:
      - STACK=development
      - DATABASE_NAME=stack-poc
      - DATABASE_URL=mongodb://mongo:27017/
    volumes:
      - ./api/:/home/api
    networks:
      - external
      - internal
    ports:
      - 4000:4000
    command: npm run deploy

  mongo:
    image: mongo
    user: mongodb
    deploy:
      replicas: 1
    volumes:
      - mongo-data:/data/db
    networks:
      - internal
    ports:
      - 27017:27017
    command: mongod

  webapp:
    image: hai5nguy/stack-poc-webapp
    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure
    environment:
      - STACK=development
      - API_URL=http://localhost:4000/graphql
    networks:
      - external
      - internal
    ports:
      - 3000:3000

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - external

networks:
  external:
  internal:

volumes:
  mongo-data:

