version: "3"
services:
  webapp:
    image: "node:8"
    user: "node"
    deploy:
      replicas: 5
      # restart_policy:
      #   condition: on-failure
    working_dir: /home/webapp
    environment:
      - NODE_ENV=production
    volumes:
      - ./webapp/:/home/webapp
    ports:
      - 8000:8000
    command: "npm run deploy"
    
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]