version: "3"
services:
  api:
    image: "node:8"
    user: "node"
    deploy:
      replicas: 1
    working_dir: /home/api
    environment:
      - STACK=production
    volumes:
      - ./api/:/home/api
    networks:
      - frontend
      - backend
    ports:
      - 4000:4000
    command: "npm run deploy"
  webapp:
    image: "node:8"
    user: "node"
    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure
    working_dir: /home/webapp
    environment:
      - STACK=production
      - API_URL=http://localhost:4000/graphql
    volumes:
      - ./webapp/:/home/webapp
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    command: "npm run deploy"
  visualizer:
    image: dockersamples/visualizer:stable
    networks:
      - frontend
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  frontend:
  backend:

